services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test
    ports:
      - "9870:9870"     # WebHDFS UI
      - "9000:9000"     # RPC
    volumes:
      - hdfs_namenode:/hadoop/dfs/name
    networks:
      - hdfsnet

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    ports:
      - "9864:9864"
    volumes:
      - hdfs_datanode:/hadoop/dfs/data
    networks:
      - hdfsnet
    depends_on:
      - namenode

  fastapi:
    build: .
    container_name: fastapi-hdfs
    environment:
      - HDFS_URL=http://namenode:9870/webhdfs/v1
      - HDFS_USER=hdfs
    ports:
      - "8000:8000"
    networks:
      - hdfsnet
    depends_on:
      - namenode
      - datanode

volumes:
  hdfs_namenode:
  hdfs_datanode:

networks:
  hdfsnet:
